### ISSUE TITLE
Disconnect with IP interface after a while

### ISSUE THREAD

**Issue by whxciotw** [Supergiovane/node-red-contrib-knx-ultimate#134] opened 2021-08-23 02:20 UTC
**Salutation (i'll not respond to users that doesn’t wrote at least "Hello")**
Hello, Dear author,

**Describe the bug**
I am using a KNX/IP interface with 5 tunnels. Once connected, the node works fine. 
However, after a while, the node shows dicconnected with the interface, and cannot control anymore.
If I restart the nodered or the flow, the node come back to normal. But still will disconnect after a while.
During this period, the nodered is the only client connected to the interface.

**Knx-Ultimate Version**
 Latest

**Are you running node-red behind homematic, docker or anything similar?**
Pi 3B+, Pi OS, nodered on Docker

**Comment by Supergiovane** [comment] 2021-08-23 05:05
Hi
Since when you have this issue?

**Comment by whxciotw** [comment] 2021-08-23 05:39
> Hi
> Since when you have this issue?

Hi,
I installed this node since yesterday, and this issue happens after restarting the flow or nodered about a few hours later. 
It seems happens randomly, sometimes within 1 hour, sometimes within about 3-4 hours.

**Comment by Supergiovane** [comment] 2021-08-23 05:51
Hi
Have you installed other KNX nodes (even if not used)?
If yes, please uninstall all other KNX nodes, as this can interfere with the port used by knx-ultimate. Then restart.
If unsuccessfull, please either disable the Rpi WLAN interface or manually select the ethernet interface on the gateway config node, then restart.
If unsuccessfull, please follow this FAQs.

**Comment by whxciotw** [comment] 2021-08-23 06:37
> Hi
> Have you installed other KNX nodes (even if not used)?
> If yes, please uninstall all other KNX nodes, as this can interfere with the port used by knx-ultimate. Then restart.
> If unsuccessfull, please either disable the Rpi WLAN interface or manually select the ethernet interface on the gateway config node, then restart.
> If unsuccessfull, please follow this [FAQs.](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/de-5.-FAQ-Troubleshoot)

On other Pi, I installed other KNX nodes and working correcttly, but on this Pi, all of the software is newly installed, incluing OS, docker, nodered and KNX nodes, no other KNX nodes installed ever.
I didn't use the WLAN of the Pi and have disabled it.
Later I will try to select the ethernet interface on the gateway config node and restart.

Thanks for your reply.

**Comment by Supergiovane** [comment] 2021-08-23 06:39
Hi
If on other Pi you used KNX Nodes from other developers, please try to uninstall knx-ultimate and install it and see if it remains connected.

**Comment by songzh96** [comment] 2021-08-23 07:19
same issue 

I'm run node-red-knx-ultimate in NAS Docker， But the node can't connect the knx-IP tunnel

**Comment by Supergiovane** [comment] 2021-08-23 07:20
Hi songz.
What version of knx-ultimate are you running?

**Comment by songzh96** [comment] 2021-08-23 07:23
knx-ultimate 1.2.39
node-red 2.0.5

I install another node-red-knx lib, same issue.
So I think it is NAS Net issue

**Comment by Supergiovane** [comment] 2021-08-23 07:27
You can try to downgrade knx-ultimate to 1.2.34 or you can send me the node-red log, so i can investigate. For downgrading, please cd into your .node-red folder and issue a npm install node-red-contrib-knx-ultimate@1.2.34 on a command prompt.

I'm personally running node-red on a VM in a QNAP NAS, updated with the latest version, and it works.
If you all can, avoid using dockers, if possibile. It relies too much on the underlying NAS linux.

**Comment by songzh96** [comment] 2021-08-23 08:12
Logs
```
[error] 8/23/2021, 4:10:58 PM knxUltimate-config: connFailCb, Disconnected.
[warn] 8/23/2021, 4:10:58 PM KnxUltimate-API2: connection timed out ... reconnecting
```


runing knx-ultimate in NAS not NAS Docker
knx-ultimate v 1.2.34

**Comment by Supergiovane** [comment] 2021-08-23 08:14
Hmmm.... it tries to reconnect but nothing.
While disconnected, what happens if you ping the KNX Interface via a command prompt?

**Comment by songzh96** [comment] 2021-08-23 08:17
when disconnected, ping is ok
```
bohong-NAS@bohong-NAS:~/.node-red$ sudo ping 192.168.100.50
Password:
PING 192.168.100.50 (192.168.100.50) 56(84) bytes of data.
64 bytes from 192.168.100.50: icmp_seq=1 ttl=255 time=0.365 ms
64 bytes from 192.168.100.50: icmp_seq=2 ttl=255 time=0.283 ms
64 bytes from 192.168.100.50: icmp_seq=3 ttl=255 time=0.312 ms
64 bytes from 192.168.100.50: icmp_seq=4 ttl=255 time=0.361 ms
64 bytes from 192.168.100.50: icmp_seq=5 ttl=255 time=0.457 ms
```

**Comment by Supergiovane** [comment] 2021-08-23 08:18
Are you able to recover, by doing a full deploy i node-red?

**Comment by songzh96** [comment] 2021-08-23 08:20
nope, the same issue
strange........  but I can use 224.0.23.12 but, it will lose packages

**Comment by Supergiovane** [comment] 2021-08-23 08:25
The KNX Interface is using UDP, even in tunnelling mode, so there should be some issue on UDP transport. The fact that you can ping the interface, means that the ethernet link is up and running but something is interfering.
You should investigate what has changed in your NAS. Any security patch? Any update in the firewall?
In the meantime, i think you can safely re-upgrade to knx-ultimate 1.2.39.

**Comment by songzh96** [comment] 2021-08-23 08:38
seems like UDP is not open, Did you kown how to open it?
```
bohong-NAS@bohong-NAS:~$ netstat -tln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 127.0.0.1:33074         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:40275         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:45524         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:36404         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:42740         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:38357         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:21              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:42229         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:662             0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:39607         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:1880            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:46872         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:41497         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:41753         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:41754         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:36442         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:36602         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:41084         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:35964         0.0.0.0:*               LISTEN
tcp        0      0 192.168.100.134:3260    0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:4700          0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:892             0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:512           0.0.0.0:*               LISTEN
tcp        0      0 172.17.0.1:6881         0.0.0.0:*               LISTEN
tcp        0      0 192.168.100.134:6881    0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:6881          0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:2049            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:34434         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:37122         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:36547         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:40996         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:43780         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:45381         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:39365         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:32773           0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:40806         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:32774           0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:42344         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:873             0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:42697         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:5001            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:46635         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:38059         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:38828         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:33517         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:39213         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:5357            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:39661         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:4045            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:39758         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:44943         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:33200         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:38928         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN
tcp6       0      0 :::21                   :::*                    LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 :::662                  :::*                    LISTEN
tcp6       0      0 :::443                  :::*                    LISTEN
tcp6       0      0 fdbf:a83f:1d1e:8:2:3260 :::*                    LISTEN
tcp6       0      0 fd05:1adc:d2bc:3:2:3260 :::*                    LISTEN
tcp6       0      0 240e:37a:1f0f:9900:3260 :::*                    LISTEN
tcp6       0      0 240e:37a:1f0f:9900:3260 :::*                    LISTEN
tcp6       0      0 240e:37a:1f03:cc00:3260 :::*                    LISTEN
tcp6       0      0 240e:37a:1f03:cc00:3260 :::*                    LISTEN
tcp6       0      0 fe80::211:32ff:fed:3260 :::*                    LISTEN
tcp6       0      0 :::892                  :::*                    LISTEN
tcp6       0      0 :::8989                 :::*                    LISTEN
tcp6       0      0 :::3261                 :::*                    LISTEN
tcp6       0      0 :::445                  :::*                    LISTEN
tcp6       0      0 :::3263                 :::*                    LISTEN
tcp6       0      0 :::41536                :::*                    LISTEN
tcp6       0      0 :::3264                 :::*                    LISTEN
tcp6       0      0 fd05:1adc:d2bc:3:2:6881 :::*                    LISTEN
tcp6       0      0 :::43009                :::*                    LISTEN
tcp6       0      0 240e:37a:1f0f:9900:6881 :::*                    LISTEN
tcp6       0      0 240e:37a:1f0f:9900:6881 :::*                    LISTEN
tcp6       0      0 fe80::f0ee:ebff:fe:6881 :::*                    LISTEN
tcp6       0      0 fe80::a8fa:e7ff:fe:6881 :::*                    LISTEN
tcp6       0      0 fe80::e89e:aeff:fe:6881 :::*                    LISTEN
tcp6       0      0 fe80::42:a5ff:fe70:6881 :::*                    LISTEN
tcp6       0      0 fe80::211:32ff:fed:6881 :::*                    LISTEN
tcp6       0      0 240e:37a:1f03:cc00:6881 :::*                    LISTEN
tcp6       0      0 240e:37a:1f03:cc00:6881 :::*                    LISTEN
tcp6       0      0 ::1:6881                :::*                    LISTEN
tcp6       0      0 :::3265                 :::*                    LISTEN
tcp6       0      0 :::2049                 :::*                    LISTEN
tcp6       0      0 :::548                  :::*                    LISTEN
tcp6       0      0 :::8581                 :::*                    LISTEN
tcp6       0      0 :::45576                :::*                    LISTEN
tcp6       0      0 :::5000                 :::*                    LISTEN
tcp6       0      0 :::873                  :::*                    LISTEN
tcp6       0      0 :::5001                 :::*                    LISTEN
tcp6       0      0 :::139                  :::*                    LISTEN
tcp6       0      0 :::41292                :::*                    LISTEN
tcp6       0      0 :::5357                 :::*                    LISTEN
tcp6       0      0 :::42925                :::*                    LISTEN
tcp6       0      0 :::4045                 :::*                    LISTEN
tcp6       0      0 :::111                  :::*                    LISTEN
tcp6       0      0 :::53776                :::*                    LISTEN
tcp6       0      0 :::80                   :::*                    LISTEN
```

**Comment by Supergiovane** [comment] 2021-08-23 08:43
It depends on your NAS. I think you should search on internet, how to do it.
But... if some UDP packets pass your NAS, for me  it has something to do with packet throttling, rate limiter or something like this.

**Comment by whxciotw** [comment] 2021-08-24 00:49
I guess this issue is not related to UDP service of OS.
Because when I restart the flow or nodered, the KNX nodes works fine, and the OS shows the same log as songzh.

**Comment by songzh96** [comment] 2021-08-24 03:47
Hi @Supergiovane 
I also did a test on the pc, but it still can’t connect

**failed** 
WIN7
node-red 2.0.5
knx-ulimate 1.2.39


**failed** 
WIN7
node-red 1.3.6
knx-ulimate 1.2.39

**failed** 
WIN7
node-red 1.3.6
knx-easy 0.10.0


But the strange thing is that I can use the multicast protocol. And I can connect in the ETS software
![image](https://user-images.githubusercontent.com/26770241/130552684-da551c6d-96a7-4e51-90c7-fd886bfa8434.png)

**Comment by Supergiovane** [comment] 2021-08-24 04:28
Hi to both of you two. 
I need you to set the debug level to “info” in the gateway config setting, restart nodered and post the full log as attachment to this thread, once the problem appears. Thank you.

**Comment by songzh96** [comment] 2021-08-24 04:46
Hi this is the logs (info)
```
24 Aug 12:37:47 - [info] Starting flows
[info] 2021-8-24 12:37:47 PM KNXUltimate-config: payload cache set to \Users\Adm
inistrator\.node-red\knxultimatestorage\knxpersistvalues
[info] 2021-8-24 12:37:47 PM KNXUltimate-config: Bind KNX Bus to interface (Auto
). Node Multicast KNX Gateway
[info] 2021-8-24 12:37:47 PM knxUltimate-config: Will connect in 6 secs. with Mu
lticast KNX Gateway
24 Aug 12:37:47 - [info] Started flows
24 Aug 12:37:47 - [info] Server now running at http://127.0.0.1:1880/
[info] 2021-8-24 12:37:53 PM knxUltimate-config: perform websocket connection on
 Multicast KNX Gateway
[error] 2021-8-24 12:37:58 PM knxUltimate-config: connFailCb, Disconnected.
[info] 2021-8-24 12:37:58 PM KNXUltimate-config: Bind KNX Bus to interface (Auto
). Node Multicast KNX Gateway
[info] 2021-8-24 12:37:58 PM knxUltimate-config: Will connect in 7 secs. with Mu
lticast KNX Gateway
[warn] 2021-8-24 12:37:58 PM KnxUltimate-API2: connection timed out ... disconne
cting
[info] 2021-8-24 12:38:05 PM knxUltimate-config: perform websocket connection on
 Multicast KNX Gateway
[error] 2021-8-24 12:38:10 PM knxUltimate-config: connFailCb, Disconnected.
[info] 2021-8-24 12:38:10 PM KNXUltimate-config: Bind KNX Bus to interface (Auto
). Node Multicast KNX Gateway
[info] 2021-8-24 12:38:10 PM knxUltimate-config: Will connect in 7 secs. with Mu
lticast KNX Gateway
[warn] 2021-8-24 12:38:10 PM KnxUltimate-API2: connection timed out ... disconne
cting
```

this is Logs (Debug)
```
[debug] 2021-8-24 12:45:01 PM KnxUltimate-API2: *** deferring Until
"inputType":"inbound_DISCONNECT_RESPONSE","delegated":false}
[debug] 2021-8-24 12:45:01 PM KnxUltimate-API2: got connect respons
[error] 2021-8-24 12:45:03 PM knxUltimate-config: connFailCb, Disco
[info] 2021-8-24 12:45:03 PM KNXUltimate-config: Bind KNX Bus to in
线网络连接 (Interface's name selected from dropdown list). Node Mul
teway
[debug] 2021-8-24 12:45:03 PM KnxUltimate-API2: initializing privat
to 192.168.100.201
[info] 2021-8-24 12:45:03 PM knxUltimate-config: Will connect in 5
lticast KNX Gateway
[warn] 2021-8-24 12:45:03 PM KnxUltimate-API2: connection timed out
cting
[debug] 2021-8-24 12:45:03 PM KnxUltimate-API2: Closing socket: %s
```

**Comment by Supergiovane** [comment] 2021-08-24 05:47
Hi Songz
there is nothing strange in the logs. The connection simply times out because the KNX Interface fail to respond.
I ask you the same things, because it's important:Since when, the issue appeared?
Then:
Are you sure not to have ran out of tunnels? 
Have you tried to leave ETS closed, restart the KNX IP Interface, restart node-red (with the knx-ultimate gateway set to 192.168.100.201) and leave it all alone running?

**Comment by songzh96** [comment] 2021-08-24 07:26
**Details**
Before I used the KNX-IP I made myself（Raspberry + knxd）This can use the KNX unicast protocol. , and one day this device broke down, So I bought a KNX router, So I bought a KNX router and found that knx-ultimate cannot use KNX unicast protocol

**Answer**
1. Not out of range
![image](https://user-images.githubusercontent.com/26770241/130573484-1e18822f-add3-4ed1-b597-f97c98f7189d.png)
![image](https://user-images.githubusercontent.com/26770241/130573686-ca2f6374-6b7f-4dc8-98fb-25896b59a68e.png)

2. I have tested it and still can’t connect

I think this is not knx-ultimate issue，But I’m very confused, I don’t know where the problem is

**Comment by Supergiovane** [comment] 2021-08-24 07:36
Hi Songzh
i can assure you, that knx-ultimate works either in multicast and unicast and it's very solid. 
What make/model of knx router are you using?
Please make sure that your switch where knx interface and node-red are connected to, doesn't have any UDP storm protection enabled.

**Comment by Supergiovane** [comment] 2021-08-24 09:03
PS: you can also try to change the physical address in the knx-ultimate gateway config. The default should be 15.15.1. Change it to reflect the physical address "subnet" of your knx interface.

**Comment by songzh96** [comment] 2021-08-24 09:07
> PS: you can also try to change the physical address in the knx-ultimate gateway config. The default should be 15.15.1. Change it to reflect the physical address's "subnet" of your knx interface (for example 1.1.249).

No, no, it's definitely not the problem here. Because I tested several KNX libraries, they were all unlinkable.

By the way, are you interested in making knx's commercial gateway?
My personal email address is 986758232@qq.com.

**Comment by Supergiovane** [comment] 2021-08-24 09:15
Hi Songzh,
thank you but no, sorry. I have absolutely no time! :-(

**Comment by Supergiovane** [comment] 2021-08-24 09:39
> I guess this issue is not related to UDP service of OS.
> Because when I restart the flow or nodered, the KNX nodes works fine, and the OS shows the same log as songzh.

I need you to set the debug level to “info” in the gateway config setting, restart nodered and post the full log as attachment to this thread, once the problem appears. Thank you.

**Comment by whxciotw** [comment] 2021-08-25 10:36
> > I guess this issue is not related to UDP service of OS.
> > Because when I restart the flow or nodered, the KNX nodes works fine, and the OS shows the same log as songzh.
> 
> @whxciotw I need you to set the debug level to “info” in the gateway config setting, restart nodered and post the full log as attachment to this thread, once the problem appears. Thank you.

OK, thanks.
I am recording the log, once the error occurs, I will upload the logs.

**Comment by Supergiovane** [comment] 2021-08-25 11:12
A question for boht of you: do you have imported the ETS group address file?

**Comment by songzh96** [comment] 2021-08-25 11:15
> A question for boht of you: do you have imported the ETS group address file?

Yes, I did.
However, I didn't import it when I tested it on my PC

**Comment by Supergiovane** [comment] 2021-08-25 12:43
Hi songzh,
can you please unzip this file into your **.node-red/node_modules/node-red-contrib-knx-ultimate/nodes** folder, restart node-red and see if it solved^

[knxUltimate-config.js.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/7047006/knxUltimate-config.js.zip)

**Comment by Supergiovane** [comment] 2021-08-25 13:23
Hey both,
V. 1.2.40 is out.
Please upgrade to this version and let le know if it solved your issue.

**Comment by songzh96** [comment] 2021-09-03 07:51
Hi @Supergiovane 
I found this problem，My knx-ip gateway firmware does not support net link, it has been fixed now.

**Comment by Supergiovane** [comment] 2021-09-03 08:35
Thank you for the update.

**Comment by Supergiovane** [comment] 2021-09-11 05:20
> > A question for boht of you: do you have imported the ETS group address file?
> 
> No. I didn't import the group address file.

Hi
Can you give me a feedback?

**Closed** 2021-09-13 09:02 UTC
