### ISSUE TITLE
Error message when using two Hue-Bridges in parallel

### ISSUE THREAD

**Issue by bschmid-hue** [Supergiovane/node-red-contrib-knx-ultimate#315] opened 2024-01-06 11:08 UTC
**Salutation (i'll not respond to users that doesn’t wrote at least "Hello")**
Hello Supergiovane, 
thanks for this great project, I just migrated my own Hue KNX setup to your setup and it works perfect.

**Describe the bug**
When adding a 2nd hue bridge and selecting a hue group or light after some sec the error "Please close and reload ..." is shown

**To Reproduce**
1. add a second hue bridge
2. add a new hue light node
3. select the second hue bride
4. select a light
5. error message is shown

**Expected behavior**

**Screenshots**
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/75546382/4bb3390c-e787-4244-ab80-534c651d2b42)

**Knx-Ultimate Version**
 - 2.3.4

**Are you running node-red behind homematic, docker or anything similar?**
 - Node-Red on proxmox

**Additional context**
- running the two bridges on two seperate node-red instances works.

**Comment by Supergiovane** [comment] 2024-01-06 11:23
Hi
Does the problem presists, even if you wait some seconds and retry?

**Comment by Supergiovane** [comment] 2024-01-06 11:34
I cannot reproduce the issue. Colud you please make a short video, so i can better understand?
Thank you!!

**Comment by bschmid-hue** [comment] 2024-01-06 13:21
Of course, I will do the recording later. I checked the developer mode:

knxUltimateGetLightObject?id=a564e390-4cb8-469b-9e96-f36c75403b23&[object%20Object]

 

returns an empty object {}

 

Björn

 

Von: Massimo Saccani ***@***.***> 
Gesendet: Samstag, 6. Januar 2024 12:35
An: Supergiovane/node-red-contrib-knx-ultimate ***@***.***>
Cc: bschmid-hue ***@***.***>; Author ***@***.***>
Betreff: Re: [Supergiovane/node-red-contrib-knx-ultimate] Error message when using two Hue-Bridges in parallel (Issue #315)

 

I cannot reproduce the issue. Colud you please make a short video, so i can better understand?
Thank you!!

**Comment by Supergiovane** [comment] 2024-01-06 13:45
Hi
Yes i saw that but i’m unable to replicate the problem, so i’ve asked you about the video. 😉

**Comment by bschmid-hue** [comment] 2024-01-06 14:15
recording:
https://1drv.ms/v/s!AqoOIjT7n8uNgs5_-jnxIhI-kNbJNQ?e=O8LXnO

**Comment by Supergiovane** [comment] 2024-01-06 18:57
Hi
It's fixed in the v. 2.3.5 out now.
Cheers.

**Closed by Supergiovane** 2024-01-06 18:57 UTC
