### ISSUE TITLE
Alerter does not catch status of controlled GAs after deploy

### ISSUE THREAD

**Issue by jomifa** [Supergiovane/node-red-contrib-knx-ultimate#406] opened 2024-12-04 14:48 UTC
**Salutation (i'll not respond to users that doesn’t wrote at least "Hello")**

**Describe the bug**
Write here a clear and concise description of what the bug is.
Hi,
Transfer of the attached data

**To Reproduce**
Write here the steps to reproduce the behavior, for example:

**Expected behavior**
Write here a clear and concise description of what you expected to happen.

**Screenshots**
Here, if applicable, add screenshots to help explain your problem.

**Knx-Ultimate Version**
 - Eg. 2.3.5

**Are you running node-red behind homematic, docker or anything similar?**
 - Eg. Node-Red running alone in RaspberryPi

**Additional context**
Write here any other context about the problem here.
![Diagnose](https://github.com/user-attachments/assets/49e9129b-9278-432e-87e1-8c18322f5ec1)
![node red Definitionen](https://github.com/user-attachments/assets/708451b4-3988-4b51-b082-ecf4b35ce37b)
![alerter Definitionen](https://github.com/user-attachments/assets/7c8d60ba-a75c-4bd0-b2f0-ac32618c9aff)

**Comment by Supergiovane** [comment] 2024-12-04 15:04
Hi
the latest knx ultimate is 3.3.6, not 2.3.5
Are you running the 3.3.6?

**Comment by jomifa** [comment] 2024-12-04 16:46
Hi,
i have simply left the example here. Of course, I have installed the previously received 3.3.5 fix. Don't you remember my error description in the previous issue?

**Comment by jomifa** [comment] 2024-12-04 16:47
I mean of course 3.3.6

**Comment by Supergiovane** [comment] 2024-12-05 07:30
#404

**Comment by Supergiovane** [comment] 2024-12-05 07:42
Hi
i've tested deploying the flow, but the alerter still work.

https://github.com/user-attachments/assets/5dbf9f54-c08f-4b74-9c8b-f20cf30b15f6

As i clearly don't understand what your problem is, please make a video explaining where the problem is.

**Comment by jomifa** [comment] 2024-12-05 10:27
Hi,
I don't know what there is to understand.

So here is the procedure for the KNX Alerter again:

- The KNX Alerter displays a lighting that is switched on
- Then a deploy takes place through flow changes
- the KNX Alerter checks its specified GAs, which can be seen in the KNX diagnosis of the ETS and receives a corresponding response that a lighting is already switched on (you already have this information)
- in the node red flow you can see that the KNX Alerter still has the status for the affected GA set to Read. This status remains persistent 

Conclusion:
the KNX Alerter no longer shows the lighting switched on

The video I have created is approx. 80MB in size. Github can only save videos up to 10MB. If you give me an e-mail address that can receive 80MB, please let me know.

**Comment by Supergiovane** [comment] 2024-12-05 10:43
But your problem is the status only? So, the flow works as expected, but only the status doesn't change?

**Comment by jomifa** [comment] 2024-12-05 12:05
hi,
no, no, it is not only the status but also the consequence that the KNX Alerter does not recognize the lighting as switched on. For this reason, no information is provided when the KNX Alerter is queried. The outputs are all not set. It knows nothing about the lighting being switched on. It only registers when the lighting is switched off and on again.



Von: Massimo Saccani ***@***.***>
Gesendet: Donnerstag, 5. Dezember 2024 11:44
An: Supergiovane/node-red-contrib-knx-ultimate ***@***.***>
Cc: Joachim Fach ***@***.***>; Author ***@***.***>
Betreff: Re: [Supergiovane/node-red-contrib-knx-ultimate] Alerter does not catch status of controlled GAs after deploy (Issue #406)


But your problem is the status only? So, the flow works as expected, but only the status doesn't change?

**Comment by jomifa** [comment] 2024-12-05 12:40
hi,
I have tried to narrow down the error situation a little. I noticed that the problem occurs when the deploy is carried out completely. On the other hand, if the deploy is carried out on changed flows, the state of the lighting is recognized by the KNX Alerter.

Please check this situation.

**Comment by Supergiovane** [comment] 2024-12-05 14:34
Hi
if you press full deploy, each node is de-registered and re-registered, each connection is closed then reopened. I suggest you to never do a full deploy.
Anyway, even with full deployment, the alerter resumes the standard behaviour. In this case, it takes longer, because the KNX Gateway is disconnected first, then reconnected prior to issue a read telegram. Anyway, i've tested it yet also a full deploy and it works.

**Comment by Supergiovane** [comment] 2024-12-07 16:00
Hi
have you checked the matter? Can i close the issue?

**Comment by jomifa** [comment] 2024-12-07 16:57
Hi,
for me, this is still a mistake:

1. the color of the KNX Alerter is blue and not red although monitored GAs have the value 1
2. during a full deploy the KNX Alerter does not work in the start phase

I have found a solution for point 2. Only deploys for changed flows!

Decide for yourself how you want to proceed.


Von: Massimo Saccani ***@***.***>
Gesendet: Samstag, 7. Dezember 2024 17:01
An: Supergiovane/node-red-contrib-knx-ultimate ***@***.***>
Cc: Joachim Fach ***@***.***>; Author ***@***.***>
Betreff: Re: [Supergiovane/node-red-contrib-knx-ultimate] Alerter does not catch status of controlled GAs after deploy (Issue #406)


Hi
have you checked the matter? Can i close the issue?

**Comment by Supergiovane** [comment] 2024-12-07 17:09
Hi,
There must be something wrong, because after a full deploy, the node issue a new read command and updates the values. This take some time, but it must work (at least, my two VM's, one with pure node-red and the other with HA + node red, are working fine).

About the status color, i'll take a note of that, but if you could make a short video, with an alerter node linked to a debug node and status node, where you push "full deploy", i can see the status sequence and what is happening. It could be very useful, because the node doesn't log the status changes.
Something like this:

![Node-RED___Flow_1](https://github.com/user-attachments/assets/8a4362f1-7a9f-4bde-8cba-87aea4141dd8)

With the status node set like this:

![Node-RED___Flow_1](https://github.com/user-attachments/assets/778aa2ee-fcb8-46e2-9d04-d24def402970)

**Comment by jomifa** [comment] 2024-12-07 17:53
Hi,
I have added the Status Node to the flow for a KNX Alerter. (see attached screenshots)

![flow](https://github.com/user-attachments/assets/9eec3928-d433-418b-8f3a-3985da8a364d)
![debug](https://github.com/user-attachments/assets/ac5b455e-b88a-4de9-aa9b-e3667ac5975b)
![node status](https://github.com/user-attachments/assets/ee5cd49f-c897-4bcd-bd8e-bd4e1304791e)

**Comment by Supergiovane** [comment] 2024-12-07 18:30
Hi
meiner Meinung nach, the node is receiving some invalid input msg payload from the flow. 
The status doesn’t have any sense. There are only “undefined”.

**Closed** 2024-12-25 09:02 UTC
