### ISSUE TITLE
HUE Tunable White Status is not working

### ISSUE THREAD

**Issue by KoljaW** [Supergiovane/node-red-contrib-knx-ultimate#355] opened 2024-05-09 09:46 UTC
Hello :) First i would like to say THANK YOU for this awesome integration..

**Describe the bug**
I am able to control kelvin in the tunable white tab, but in my ETS debug monitor i always get 13222 K back as a feedback in the status adress. 

**Screenshots**
![ETS_HUE](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/76074195/ee7a7d73-e422-4d4d-b30d-320cb6ff1f6e)
![NodeRed_HUE](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/76074195/988c1d3e-20dc-4ec7-9dd3-9c9e19c4ab3d)

**Knx-Ultimate Version**
 - 2.4.22

**Are you running node-red behind homematic, docker or anything similar?**
 - Node-Red running alone in RaspberryPi (iobroker adapter)

**Comment by Supergiovane** [comment] 2024-05-09 09:49
Hi
thanks for using my node.
I'll check it immediately.

**Comment by Supergiovane** [comment] 2024-05-09 10:37
Hi again.
node-red-contrib-knx-ultimate@2.4.24 is out with the fix.
Please re-open this issue is you encounter problems.
;-)

**Comment by KoljaW** [comment] 2024-05-09 11:24
Unfortunately now i get always 6535 Kelvin back on my feedback address. No matter what i type in.

![ETS_HUE_neu](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/76074195/32d25e93-3b04-4410-94f5-d22021f9f489)

**Comment by Supergiovane** [comment] 2024-05-09 11:43
Hi
can i see your fow?
Cab you paste it here?

**Comment by KoljaW** [comment] 2024-05-09 11:53
Its just a single Node(Flow) controlled by KNX. 

![1](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/76074195/790048d3-d22d-43a7-b3e7-bc20db74fc7d)
![2](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/76074195/82dc5031-48fd-4265-a71c-fa77451a1d6c)
![3](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/76074195/8e007113-91ce-4273-841d-012d72d17e49)
![4](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/76074195/587a135c-952b-4921-9c0f-fb8acec909df)
![5](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/76074195/7998bb71-82d4-4ef5-8f5d-eccc54129808)
![6](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/76074195/e2f53135-371e-402b-87f3-22f17fb4e5ea)

**Comment by Supergiovane** [comment] 2024-05-09 11:56
Good. Thank you. 
I'll try duplicating all your setting and i'll see. If you paste the json code, use the "<>" button, so i can then copy the flow.

**Comment by KoljaW** [comment] 2024-05-09 12:00
`[
    {
        "id": "d9b9e21fd974187d",
        "type": "knxUltimateHueLight",
        "z": "cee66af809874694",
        "server": "7812b80dbdc8e7d3",
        "serverHue": "a7e686213e3bfafb",
        "name": "Grouped_light: Wohnzimmer Fenster (Zone)",
        "nameLightSwitch": "E6 Wohnzimmer Wandbeleuchtung Esstisch HUE Schalten",
        "GALightSwitch": "5/1/60",
        "dptLightSwitch": "1.001",
        "nameLightState": "E6 Wohnzimmer Wandbeleuchtung Esstisch HUE Schalten Status",
        "GALightState": "5/2/60",
        "dptLightState": "1.001",
        "nameLightDIM": "",
        "GALightDIM": "",
        "dptLightDIM": "",
        "nameLightColor": "",
        "GALightColor": "",
        "dptLightColor": "232.600",
        "nameLightColorState": "",
        "GALightColorState": "",
        "dptLightColorState": "232.600",
        "nameLightHSV_H_DIM": "",
        "GALightHSV_H_DIM": "",
        "dptLightHSV_H_DIM": "",
        "nameLightHSV_H_State": "",
        "GALightHSV_H_State": "",
        "dptLightHSV_H_State": "",
        "nameLightHSV_S_DIM": "",
        "GALightHSV_S_DIM": "",
        "dptLightHSV_S_DIM": "",
        "nameLightHSV_S_State": "",
        "GALightHSV_S_State": "",
        "dptLightHSV_S_State": "",
        "nameLightKelvinDIM": "",
        "GALightKelvinDIM": "",
        "dptLightKelvinDIM": "",
        "nameLightKelvinPercentage": "",
        "GALightKelvinPercentage": "",
        "dptLightKelvinPercentage": "",
        "nameLightKelvinPercentageState": "",
        "GALightKelvinPercentageState": "",
        "dptLightKelvinPercentageState": "",
        "nameLightKelvin": "E6 Wohnzimmer Wandbeleuchtung Esstisch HUE Farbtemperatur",
        "GALightKelvin": "5/5/60",
        "dptLightKelvin": "7.600",
        "nameLightKelvinState": "E6 Wohnzimmer Wandbeleuchtung Esstisch HUE Farbtemperatur Status",
        "GALightKelvinState": "5/5/61",
        "dptLightKelvinState": "7.600",
        "nameLightBrightness": "E6 Wohnzimmer Wandbeleuchtung Esstisch HUE Helligkeit Relativ",
        "GALightBrightness": "5/3/60",
        "dptLightBrightness": "5.001",
        "nameLightBrightnessState": "E6 Wohnzimmer Wandbeleuchtung Esstisch HUE Helligkeit Relativ Status",
        "GALightBrightnessState": "5/3/61",
        "dptLightBrightnessState": "5.001",
        "nameLightBlink": "",
        "GALightBlink": "",
        "dptLightBlink": "",
        "nameLightColorCycle": "",
        "GALightColorCycle": "",
        "dptLightColorCycle": "",
        "nameDaylightSensor": "Tag=0 / Nacht=1 Schlafzimmer Gesamt",
        "GADaylightSensor": "0/5/5",
        "dptDaylightSensor": "1.003",
        "specifySwitchOnBrightness": "temperature",
        "colorAtSwitchOnDayTime": "{ \"kelvin\":2700, \"brightness\":100 }",
        "enableDayNightLighting": "temperature",
        "colorAtSwitchOnNightTime": "{ \"kelvin\":2700, \"brightness\":10 }",
        "invertDayNight": true,
        "invertDimTunableWhiteDirection": false,
        "updateKNXBrightnessStatusOnHUEOnOff": "onhueoff",
        "dimSpeed": 5000,
        "HSVDimSpeed": 5000,
        "minDimLevelLight": "0",
        "maxDimLevelLight": 100,
        "readStatusAtStartup": "yes",
        "enableNodePINS": "yes",
        "outputs": 1,
        "inputs": 1,
        "hueDevice": "65ef3903-e387-46cd-8ec8-e9b0f570051e#grouped_light",
        "hueDeviceObject": {},
        "x": 410,
        "y": 840,
        "wires": [
            []
        ]
    },
    {
        "id": "7812b80dbdc8e7d3",
        "type": "knxUltimate-config",
        "host": "192.168.30.31",
        "port": "3700",
        "physAddr": "15.15.22",
        "hostProtocol": "TunnelUDP",
        "suppressACKRequest": false,
        "csv": "",
        "KNXEthInterface": "Auto",
        "KNXEthInterfaceManuallyInput": "",
        "stopETSImportIfNoDatapoint": "skip",
        "loglevel": "error",
        "name": "KNX Gateway",
        "localEchoInTunneling": true,
        "delaybetweentelegrams": "50",
        "delaybetweentelegramsfurtherdelayREAD": "1",
        "ignoreTelegramsWithRepeatedFlag": false,
        "autoReconnect": "yes"
    },
    {
        "id": "a7e686213e3bfafb",
        "type": "hue-config",
        "host": "192.168.30.12",
        "name": "Hue Bridge",
        "bridgeid": "ECB5FAFFFE00A9AB"
    }
]`

**Comment by Supergiovane** [comment] 2024-05-09 12:20
Hi, cannot reproduce your issue.
I've tried sending the telegram using node-red and also using ETS.
The feedback follows the right value.

https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/acf85dfe-bfe2-444c-a66d-95ccd7645a0d

Do you maybe have other nodes 5/5/61 or 5/5/60 with a different datapoint than 7.600 in all your flows?

**Comment by Supergiovane** [comment] 2024-05-09 12:25
No, stop.
I've understood what you're doing. You're making a READ request to 5/5/61
I also receive 6565 in this case.
Please hold on, i'm ditching into it....

**Comment by KoljaW** [comment] 2024-05-09 12:43
Maybe a KNX Problem? 


https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/76074195/44a9cc5c-c78e-4a12-88d0-ca6eb8bd1253

**Comment by Supergiovane** [comment] 2024-05-09 12:49
I'm testing.... will back to you asap.

**Comment by Supergiovane** [comment] 2024-05-09 12:54
I'ts related to the grouped lights.
In HUE, it doesn't exist a device representing a group, but instead, the group is a collection of light objects.
Usually, when the device is a grouped_lights, i get the first device in the collection and read the requested property. In the "kelvin read" case, however, i don't do that by mistake (i forgot it).
I'm fixing the code.

**Comment by Supergiovane** [comment] 2024-05-10 15:59
I'm about to finish. It took lnoger than expected!

**Comment by Supergiovane** [comment] 2024-05-10 17:11
Should be fixed in 2.4.26 out now.

**Comment by KoljaW** [comment] 2024-05-10 17:55
@Supergiovane 
Hello,

Oh no. something went wrong. I have no connection to my hue bridge and its not possible to setup a connection anymore. 

<img width="675" alt="Bildschirmfoto 2024-05-10 um 19 53 39" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/76074195/108959be-e279-4c3d-b5ba-1b5b580df748">

**Comment by Supergiovane** [comment] 2024-05-10 17:59
Shit….. downgrade to the previous version

**Comment by Supergiovane** [comment] 2024-05-10 18:11
Mine upgraded without issues.
Can you tell me, what the log says?

**Comment by Supergiovane** [comment] 2024-05-10 18:22
It was a Matter protocol refuse. 2.4.27 should be ok.

**Comment by Supergiovane** [comment] 2024-05-10 18:31
You can also comment this row
`
//const { AsyncObservable } = require("@project-chip/matter-node.js/util");

`
**in the .node-red/node_modules/node-red-contrib-knx-ultimate/nodes/hue-config.js**
Then restart node-red

**Comment by KoljaW** [comment] 2024-05-10 18:48
Upgrade to 2.4.27 and everything is fine. 

Also the original issue (tunable white feedback with grouped hue lights) is now working fine !!!

THANK YOU!!!

**Comment by Supergiovane** [comment] 2024-05-10 19:12
If you encounter strange behaviour, you can revert to 2.4.23 by installing the new 2.4.28 version. Is a temporary revert, better to solve the issues you encountered.

**Closed** 2024-05-11 20:12 UTC
