### ISSUE TITLE
timed out waiting for CONNECTIONSTATE_RESPONSE

### ISSUE THREAD

**Issue by heleon19** [Supergiovane/node-red-contrib-knx-ultimate#30] opened 2020-02-05 07:38 UTC
Hi Supergiovane

After Node-RED starts I can send and receive telegrams. After a deploy the following error occurs.

The connection is only restored after a restart of Node-RED.

Node-RED: v0.20.8
knx ultimate: v1.1.25

> 
3 Feb 16:52:07 - [info] Started flows
3 Feb 16:52:08 - [error] knxUltimate: Lost link due to a connection error
3 Feb 16:52:08 - [error] knxUltimate: Lost link due to a connection error
3 Feb 18:54:55 - [error] knxUltimate: knxConnection error: timed out waiting for CONNECTIONSTATE_RESPONSE
3 Feb 18:58:13 - [error] knxUltimate: knxConnection error: timed out waiting for CONNECTIONSTATE_RESPONSE
3 Feb 21:59:33 - [error] knxUltimate: knxConnection error: timed out waiting for CONNECTIONSTATE_RESPONSE
3 Feb 22:47:13 - [error] knxUltimate: knxConnection error: timed out waiting for CONNECTIONSTATE_RESPONSE
[warn] 2020-02-04 01:09:50.034 connection timed out, retrying...
4 Feb 06:52:55 - [error] knxUltimate: knxConnection error: timed out waiting for CONNECTIONSTATE_RESPONSE
4 Feb 07:07:14 - [error] knxUltimate: knxConnection error: timed out waiting for CONNECTIONSTATE_RESPONSE
4 Feb 09:27:55 - [info] Stopping flows
4 Feb 09:27:55 - [info] Stopped flows
4 Feb 09:27:55 - [info] Starting flows
4 Feb 09:27:55 - [info] knxUltimate: no csv ETS found
4 Feb 09:27:55 - [info] knxUltimate: Bind KNX Bus to interface (Auto)
4 Feb 09:27:59 - [info] Started flows
4 Feb 09:28:00 - [error] knxUltimate: Lost link due to a connection error
4 Feb 09:28:00 - [error] knxUltimate: Lost link due to a connection error
4 Feb 09:32:05 - [error] knxUltimate: knxConnection error: timed out waiting for CONNECTIONSTATE_RESPONSE
[warn] 2020-02-04 09:13:39.585 connection timed out, retrying...

>

**Comment by Supergiovane** [comment] 2020-02-05 07:47
Hello
you're having so many trouble that i need more info about your system:
How many ethernet ports do you have in your container?
What make/model of KNX/IP Router are you using?
Please take a screenshot of the node-config screen.
Thank you.

**Comment by Supergiovane** [comment] 2020-02-05 08:13
Please issue a
node -v
command as well and tell me the result. Thanks.

**Comment by heleon19** [comment] 2020-02-05 08:41
Tank you for your support

- I use Docker on a RPI, so I have LAN and WAN. I've set eth0 manually.
- IP interface Theben 9070981
- Node v11.9.0

![image](https://user-images.githubusercontent.com/10326318/73825054-96c3d000-47fb-11ea-8330-62f20d4f45c3.png)

**Comment by Supergiovane** [comment] 2020-02-05 08:51
Hello
So let's check. Sorry, but we need to go step by step.
Are you sure that in the Docker, the Ethernet interface's name is eth0?
If yes, when the node is in error, what happens if you power cycle the Theben? (only the Theben).
Thanks.

**Comment by heleon19** [comment] 2020-02-05 09:01
eth0 is in Docker container available

> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
1144: eth0@if1145: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:11:00:03 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.3/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever

After power off/on still no connection. Node in state writting, but nothing happens.

**Comment by Supergiovane** [comment] 2020-02-05 09:04
Ok, let's go to next step.
From a terminal console, can you ping the 10.1.47.250?

**Comment by Supergiovane** [comment] 2020-02-05 09:15
But wait a moment.
i saw in your log, this:

> 4 Feb 09:27:55 - [info] knxUltimate: Bind KNX Bus to interface (Auto)

You should see something like:

> 5 Feb 10:14:10 - [info] knxUltimate: Bind KNX Bus to interface : eth0 (Interface's name entered by hand)

Is the log you sent me, the correct log?

**Comment by heleon19** [comment] 2020-02-05 09:29
I've changed setting from auto to hand, but the behavior remains the same.

Ping from Container ok.

At wich level the reconnect after this error is handled?

**Comment by Supergiovane** [comment] 2020-02-05 09:41
At API level. I'ts all automatic by the API.
The last resort, is to try to select "Suppress ACK Request" in the config-node.
It this still doesn't solve the issue, we'll go for a node-red update.
I think ther's something in Node-Red V0.20 that doesn't work properly.

**Comment by heleon19** [comment] 2020-02-05 09:49
"Suppress ACK Request" made no change. 
Any idea what could be the issue with V0.20?
I will try the update

**Comment by Supergiovane** [comment] 2020-02-05 10:01
No, but we've tried all logical things.
The latest whould be connect RPI ethernet direct with the Theben. You can try this if you wish.

**Comment by heleon19** [comment] 2020-02-05 10:03
After the update to v1.0.3 the knx connection is not working at all, remains in state writting. After a couple of "deploy" it starts working. Sometimes after deploy it works somethimes not.

There is no error in the log

**Comment by heleon19** [comment] 2020-02-05 10:04
Maybe I have to wait longer after deploy, will test that

**Comment by Supergiovane** [comment] 2020-02-05 10:07
Hey,
do this:
stop node-red and avoid starting at boot (if you use PM2, you can disable the autostart on boot)
Reboot the container.
Leave the container running alone for 2-3 minutes.
Manually start node-red

I suspect that the container comes up quicker as the ethernet card.

**Comment by heleon19** [comment] 2020-02-05 10:07
Let's asume I had an network issue between RPI and KNX Interface. Why would the KNX lib not automatically reconnect. The nodes are green and showing "waiting for telegram", it looks like everything is ok, but it isn't

**Comment by Supergiovane** [comment] 2020-02-05 10:08
Yes but if it's like i suspect, the ethernet comes up too late and the node doesn't detect it.

**Comment by Supergiovane** [comment] 2020-02-05 10:23
If you wish, you can enjoy the new [WatchDog node](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/7.-WatchDog-Configuration).
You can force the reconnection [like that](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/-Sample---Change-KNX-IP-config-parameters-on-the-fly), by passing the same parameters you set originally in the config node.

**Comment by heleon19** [comment] 2020-02-05 10:28
I did some testing, the connection works, but it takes up to 4 Minutes. After every deploy it takes sometimes a couple of seconds, sometimes a couple of minutes.

**Comment by Supergiovane** [comment] 2020-02-05 10:33
Slap a Watchdog node into the flow and attach to it a debug node. Then see what happens.
I assure you, that in normal conditions, the knx-ultimate stays up, automatically reconnects and that it's very reliable.

**Comment by heleon19** [comment] 2020-02-05 10:36
I'll add the Watchdog node.
I cheked the Group Monitor, after deploy and a couple of minutes the read requests and answers are send.

**Comment by Supergiovane** [comment] 2020-02-05 10:37
So can you live with that? I cannot unfortunately do nothing else for you. Or if you have suggestions to give me, i'll accept that...

**Comment by heleon19** [comment] 2020-02-05 10:45
Thank you very much for your support. Maybe we can get in touch by E-Mail for private messages?

Here the error:
![image](https://user-images.githubusercontent.com/10326318/73834850-b9aab000-480c-11ea-9109-6a664a17c1f3.png)

I will do some more tests:
- Change Port of Interface (to be sure no other App is using the Interface)
- Isolate RPI and Interface (own switch)

Thank you

**Comment by Supergiovane** [comment] 2020-02-05 10:47
Yes, pleas do that. Then let me know. We can just stay here on gitHub, this is for me better.

**Comment by Supergiovane** [comment] 2020-02-06 14:43
V 1.1.27 will come out in about 30 Minutes on npm.

**Comment by Supergiovane** [comment] 2020-02-06 14:55
But at this point, i suspect your Theben as well. Do you have maybe a spare KNX/IP **Router** to test with?

**Comment by heleon19** [comment] 2020-02-07 06:46
Thank you for merging the loglevel option and your support.

Today I will do the tests. I have several interface types in use at different locations. At the moment it looks like the underling knx.js cannot recover after some situations. 

They did some test with an bugfix brunch, but still no results. I will check the changes and test it.

https://bitbucket.org/ekarak/knx.js/branch/bugfix/issue%2371-sendTunnReq_waitACK

Here my log:
![image](https://user-images.githubusercontent.com/10326318/74007132-e4684600-497d-11ea-95be-a536e559ec44.png)

**Comment by Supergiovane** [comment] 2020-02-07 06:54
You can use the Watchdog, in the meantime. By issuing a new config, it does a reconnection.  
Please look at the wiki, the very last sample in the Navigation sidebar. 

I think it’s time to put my hands directly in the knx api.....
A question... do you maybe have two nodes with same group address but with different datapoint?

**Comment by heleon19** [comment] 2020-02-07 07:10
I had the suppress ack deactivated, will enable it for test.

The workaround with the Watchdog could be an option, but fixing the issue at the root would be the better option. 

I will run a script to check the knx nodes for wrong configurations.

**Comment by heleon19** [comment] 2020-02-07 07:49
knx nodes are ok, checked with script: 

`
const fs = require("fs");

console.log("********** ultimate config error check *************");

let flow = JSON.parse(String(fs.readFileSync("flows.json")).trim());

const node = {};

flow.filter((n) => n.type === "knxUltimate").forEach((n) => {
  if (node[n.topic] && node[n.topic] !== n.dpt) {
    console.log(`dublicated addr '${n.topic}' with different dpt '${n.dpt}'`);
  }
  const g = n.topic.split("/");
  if (g.length !== 3 || parseInt(g[0]) > 12 || parseInt(g[1]) > 7 || parseInt(g[2]) > 255) {
    console.log(`addr '${n.topic}' not valid`);
  }
  node[n.topic] = n.dpt;
});
`

**Comment by Supergiovane** [comment] 2020-02-07 07:54
Good script. Ok, the ACK should be the root cause. If you suppress it, you'll probably fine.
Other users do have issues with ACK. For that reason, i suggest to ever use an KNX Router instead of an Interface, but it cost twice :-(

**Comment by heleon19** [comment] 2020-02-07 08:28
With ACK:
![image](https://user-images.githubusercontent.com/10326318/74013216-3ca64480-498c-11ea-906f-eb7b1e18b817.png)

**Comment by Supergiovane** [comment] 2020-02-07 08:35
It’s lime before!

**Comment by heleon19** [comment] 2020-02-07 08:59
How does this look for you? This is after deploy, a lot of "deffering"

[debug] 2020-02-07 08:56:54.257 (disconnecting):        connection alive for 164.959 seconds
[trace] 2020-02-07 08:56:54.261 (disconnecting): Sending DISCONNECT_REQUEST ==> {"header_length":6,"protocol_version":16,"service_type":521,"total_length":16,"hpai":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"connstate":{"channel_id":37,"state":0}}
[trace] 2020-02-07 08:56:54.406 (disconnecting): UDP sent OK: DISCONNECT_REQUEST 06100209001025000801000000000000
[debug] 2020-02-07 08:56:54.407 (disconnecting):        sent DISCONNECT_REQUEST
[debug] 2020-02-07 08:56:54.409 Inbound message: 0610020a00082500
[trace] 2020-02-07 08:56:54.409 (disconnecting): Received DISCONNECT_RESPONSE message: {"header_length":6,"protocol_version":16,"service_type":522,"total_length":8,"connstate":{"channel_id":37,"status":0}}
[debug] 2020-02-07 08:56:54.411 (disconnecting):        got disconnect response
7 Feb 09:56:54 - [info] [mqtt-broker:29e4a851.e6fa78] Verbindung zum Broker  mqtts://mqtt.gbridge.io:8883 wurde beendet.
7 Feb 09:56:54 - [info] [loxone-miniserver:a6ce990f.08bfe8] connection closed
7 Feb 09:56:54 - [info] Flows gestoppt
7 Feb 09:56:54 - [info] Flows starten
7 Feb 09:56:54 - [info] knxUltimate: no csv ETS found
7 Feb 09:56:54 - [info] knxUltimate: Bind KNX Bus to interface (Auto)
[debug] 2020-02-07 08:56:54.616 initializing private connection to 10.1.47.251
[trace] 2020-02-07 08:56:54.619 candidate interface: eth0 ({"address":"172.17.0.3","netmask":"255.255.0.0","family":"IPv4","mac":"02:42:ac:11:00:03","internal":false,"cidr":"172.17.0.3/16"})
7 Feb 09:56:54 - [info] [fp-license:ZB hbTec, Büron - Testserver 2] last deploy = 2020-02-07 09:56
7 Feb 09:56:54 - [info] [fp-license:ZB hbTec, Büron - Testserver 2] last uptime = 2020-01-29 09:33
/hbvisu-data//logs/datalog/datalog_1bf8ab35175e75.db loaded with revision: 2
/hbvisu-data//logs/datalog/datalog_6be166fd73a998.db loaded with revision: 2
7 Feb 09:56:57 - [info] Flows gestartet
[debug] 2020-02-07 08:56:57.801 IpTunnelingConnection.BindSocket 172.17.0.3:48939
[debug] 2020-02-07 08:56:57.802 useTunneling=true
[debug] 2020-02-07 08:56:57.802 Connecting via 172.17.0.3...
[trace] 2020-02-07 08:56:57.807 (connecting): Sending CONNECT_REQUEST ==> {"header_length":6,"protocol_version":16,"service_type":517,"total_length":26,"hpai":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"tunn":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"cri":{"connection_type":4,"knx_layer":2,"unused":0},"connstate":{"state":0}}
7 Feb 09:56:58 - [error] knxUltimate: Lost link due to a connection error
7 Feb 09:56:58 - [error] knxUltimate: Lost link due to a connection error
[trace] 2020-02-07 08:56:59.563 (connecting): UDP sent OK: CONNECT_REQUEST 06100205001a0801000000000000080100000000000004040200
[debug] 2020-02-07 08:56:59.568 Inbound message: 0610020600142600080100000000000004041103
[trace] 2020-02-07 08:56:59.569 (connecting): Received CONNECT_RESPONSE message: {"header_length":6,"protocol_version":16,"service_type":518,"total_length":20,"connstate":{"channel_id":38,"status":0},"hpai":{"header_length":8,"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"cri":{"header_length":4,"connection_type":4,"knx_layer":17,"unused":3}}
[debug] 2020-02-07 08:56:59.570 got connect response
[trace] 2020-02-07 08:56:59.573 (connecting): Sending CONNECTIONSTATE_REQUEST ==> {"header_length":6,"protocol_version":16,"service_type":519,"total_length":16,"hpai":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"connstate":{"channel_id":38,"state":0}}
[debug] 2020-02-07 08:56:59.575 Inbound message: 061004200015042600002900bce0ff166000010000
[trace] 2020-02-07 08:56:59.576 (connecting): Received TUNNELING_REQUEST_L_Data.ind message: {"header_length":6,"protocol_version":16,"service_type":1056,"total_length":21,"tunnstate":{"header_length":4,"channel_id":38,"seqnum":0,"rsvd":0},"cemi":{"msgcode":41,"addinfo_length":0,"ctrl":{"frameType":1,"reserved":0,"repeat":1,"broadcast":1,"priority":3,"acknowledge":0,"confirm":0,"destAddrType":1,"hopCount":6,"extendedFrame":0},"src_addr":"15.15.22","dest_addr":"12/0/0","apdu":{"apdu_length":1,"apdu_raw":{"type":"Buffer","data":[0,0]},"tpci":0,"apci":"GroupValue_Read","data":{"type":"Buffer","data":[0]}}}}
[debug] 2020-02-07 08:56:59.577 *** deferring Until Transition {"inputType":"inbound_TUNNELING_REQUEST_L_Data.ind","delegated":false}
[debug] 2020-02-07 08:56:59.578 Inbound message: 061004200015042600002900bce0ff166000010000
[trace] 2020-02-07 08:56:59.579 (connecting): Received TUNNELING_REQUEST_L_Data.ind message: {"header_length":6,"protocol_version":16,"service_type":1056,"total_length":21,"tunnstate":{"header_length":4,"channel_id":38,"seqnum":0,"rsvd":0},"cemi":{"msgcode":41,"addinfo_length":0,"ctrl":{"frameType":1,"reserved":0,"repeat":1,"broadcast":1,"priority":3,"acknowledge":0,"confirm":0,"destAddrType":1,"hopCount":6,"extendedFrame":0},"src_addr":"15.15.22","dest_addr":"12/0/0","apdu":{"apdu_length":1,"apdu_raw":{"type":"Buffer","data":[0,0]},"tpci":0,"apci":"GroupValue_Read","data":{"type":"Buffer","data":[0]}}}}
[debug] 2020-02-07 08:56:59.580 *** deferring Until Transition {"inputType":"inbound_TUNNELING_REQUEST_L_Data.ind","delegated":false}
[debug] 2020-02-07 08:56:59.581 Inbound message: 0610020800082600
[trace] 2020-02-07 08:56:59.581 (connecting): Received CONNECTIONSTATE_RESPONSE message: {"header_length":6,"protocol_version":16,"service_type":520,"total_length":8,"connstate":{"channel_id":38,"status":0}}
[debug] 2020-02-07 08:56:59.581 Got connection state response, connstate: NO_ERROR, channel ID: 38
[debug] 2020-02-07 08:56:59.582 --- Connected in TUNNELING mode ---
[debug] 2020-02-07 08:56:59.583 (idle):  zzzz...
[trace] 2020-02-07 08:56:59.586 (recvTunnReqIndication): Sending TUNNELING_ACK ==> {"header_length":6,"protocol_version":16,"service_type":1057,"total_length":10,"hpai":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"tunnstate":{"channel_id":38,"tunnel_endpoint":"10.1.47.251:3671","seqnum":0}}
[debug] 2020-02-07 08:56:59.587 (idle):  zzzz...
[trace] 2020-02-07 08:56:59.591 (recvTunnReqIndication): Sending TUNNELING_ACK ==> {"header_length":6,"protocol_version":16,"service_type":1057,"total_length":10,"hpai":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"tunnstate":{"channel_id":38,"tunnel_endpoint":"10.1.47.251:3671","seqnum":0}}
[debug] 2020-02-07 08:56:59.592 (idle):  zzzz...
[trace] 2020-02-07 08:57:00.747 (sendDatagram): Sending TUNNELING_REQUEST_L_Data.req ==> {"header_length":6,"protocol_version":16,"service_type":1056,"total_length":21,"hpai":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"tunn":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"tunnstate":{"channel_id":38,"tunnel_endpoint":"10.1.47.251:3671","seqnum":0},"cemi":{"msgcode":17,"ctrl":{"frameType":1,"reserved":0,"repeat":1,"broadcast":1,"priority":3,"acknowledge":0,"confirm":0,"destAddrType":1,"hopCount":6,"extendedFrame":0},"src_addr":"1.1.250","dest_addr":"1/2/23","apdu":{"apci":"GroupValue_Read","tpci":0,"data":0}}}
[debug] 2020-02-07 08:57:00.748 >>>>>>> seqnum: 0
[debug] 2020-02-07 08:57:00.752 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:00.754 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:00.756 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:00.758 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:00.760 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[trace] 2020-02-07 08:57:00.761 (sendTunnReq_waitACK): UDP sent OK: CONNECTIONSTATE_REQUEST 06100207001026000801000000000000
[trace] 2020-02-07 08:57:00.763 (sendTunnReq_waitACK): UDP sent OK: TUNNELING_ACK 06100421000a04260000
[trace] 2020-02-07 08:57:00.763 (sendTunnReq_waitACK): UDP sent OK: TUNNELING_ACK 06100421000a04260000
[trace] 2020-02-07 08:57:00.764 (sendTunnReq_waitACK): UDP sent OK: TUNNELING_REQUEST_L_Data.req 061004200015042600001100bce011fa0a17010000
[debug] 2020-02-07 08:57:02.395 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.395 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.396 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.399 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.399 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.441 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.442 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.445 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.455 Inbound message: 0610042000150426010029009de0ff166000010000
[trace] 2020-02-07 08:57:02.456 (sendTunnReq_waitACK): Received TUNNELING_REQUEST_L_Data.ind message: {"header_length":6,"protocol_version":16,"service_type":1056,"total_length":21,"tunnstate":{"header_length":4,"channel_id":38,"seqnum":1,"rsvd":0},"cemi":{"msgcode":41,"addinfo_length":0,"ctrl":{"frameType":1,"reserved":0,"repeat":0,"broadcast":1,"priority":3,"acknowledge":0,"confirm":1,"destAddrType":1,"hopCount":6,"extendedFrame":0},"src_addr":"15.15.22","dest_addr":"12/0/0","apdu":{"apdu_length":1,"apdu_raw":{"type":"Buffer","data":[0,0]},"tpci":0,"apci":"GroupValue_Read","data":{"type":"Buffer","data":[0]}}}}
[debug] 2020-02-07 08:57:02.457 *** deferring inbound_TUNNELING_REQUEST_L_Data.ind until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.458 Inbound message: 06100421000a04260000
[trace] 2020-02-07 08:57:02.458 (sendTunnReq_waitACK): Received TUNNELING_ACK message: {"header_length":6,"protocol_version":16,"service_type":1057,"total_length":10,"tunnstate":{"header_length":4,"channel_id":38,"seqnum":0,"rsvd":0}}
[debug] 2020-02-07 08:57:02.459 ===== datagram 0 acknowledged by IP router
[debug] 2020-02-07 08:57:02.460 (idle):  zzzz...
[trace] 2020-02-07 08:57:02.467 (sendDatagram): Sending TUNNELING_REQUEST_L_Data.req ==> {"header_length":6,"protocol_version":16,"service_type":1056,"total_length":21,"hpai":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"tunn":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"tunnstate":{"channel_id":38,"tunnel_endpoint":"10.1.47.251:3671","seqnum":1},"cemi":{"msgcode":17,"ctrl":{"frameType":1,"reserved":0,"repeat":1,"broadcast":1,"priority":3,"acknowledge":0,"confirm":0,"destAddrType":1,"hopCount":6,"extendedFrame":0},"src_addr":"1.1.250","dest_addr":"1/1/53","apdu":{"apci":"GroupValue_Read","tpci":0,"data":0}}}
[debug] 2020-02-07 08:57:02.467 >>>>>>> seqnum: 1
[debug] 2020-02-07 08:57:02.468 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.469 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.469 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.470 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.471 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.472 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.473 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.473 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.474 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.475 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.475 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.476 *** deferring outbound_TUNNELING_REQUEST until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.477 *** deferring inbound_TUNNELING_REQUEST_L_Data.ind until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.479 Inbound message: 0610042000150426010029009de0ff166000010000
[trace] 2020-02-07 08:57:02.480 (sendTunnReq_waitACK): Received TUNNELING_REQUEST_L_Data.ind message: {"header_length":6,"protocol_version":16,"service_type":1056,"total_length":21,"tunnstate":{"header_length":4,"channel_id":38,"seqnum":1,"rsvd":0},"cemi":{"msgcode":41,"addinfo_length":0,"ctrl":{"frameType":1,"reserved":0,"repeat":0,"broadcast":1,"priority":3,"acknowledge":0,"confirm":1,"destAddrType":1,"hopCount":6,"extendedFrame":0},"src_addr":"15.15.22","dest_addr":"12/0/0","apdu":{"apdu_length":1,"apdu_raw":{"type":"Buffer","data":[0,0]},"tpci":0,"apci":"GroupValue_Read","data":{"type":"Buffer","data":[0]}}}}
[debug] 2020-02-07 08:57:02.481 *** deferring inbound_TUNNELING_REQUEST_L_Data.ind until transition sendTunnReq_waitACK => idle
[debug] 2020-02-07 08:57:02.482 Inbound message: 06100421000a04260100
[trace] 2020-02-07 08:57:02.482 (sendTunnReq_waitACK): Received TUNNELING_ACK message: {"header_length":6,"protocol_version":16,"service_type":1057,"total_length":10,"tunnstate":{"header_length":4,"channel_id":38,"seqnum":1,"rsvd":0}}

**Comment by Supergiovane** [comment] 2020-02-07 09:11
I need to ditch into this.
I'm currently the head into the "topic" matter, because i've to change a lot (Flood protection and loop prevention).
Have you tried an RPI without docker?
If you've some VM or Container capable machines, like for example a Synology or Qnap nas, you can try to download the ready to run Node-Red image and give it a try.
Never hat such as persistent issues. The magic trick was everytime either check ethernet routers for UDP storm protection, change LAN cable, enable ACK suppression or use a KNX Router.

**Comment by heleon19** [comment] 2020-02-07 15:44
I'm testing with some modifications of knx.js, will report in case i find something.

I have some questions:
1.) the function node.readInitialValues creates for each "initialread node" a setTimeout. This timeout is not cleand-up while deploy. 100 nodes will take for example 20 Seconds, so if I redeploy after 10s some timeouts are invoked afterwards? Do I something miss?

2.) once the loop detection is triggered the node is locked until next deploy? Would it be an option to release it after a reconnect?

**Comment by Supergiovane** [comment] 2020-02-07 16:15
Hello Heleon
1. No release. 
2. Ok, will invent something to unlock it.

**Comment by Supergiovane** [comment] 2020-02-10 08:01
Hello Heleon
an update is on its way on the underlying API. As soon as it'll be released, i'll push a new version.

**Comment by Supergiovane** [comment] 2020-02-17 08:45
Hello Reto
i forked the knx.js API and i created a new repo [knxultimateapi](https://bitbucket.org/maxsupergiovane/knxultimateapi/src/master/), to be able to push out updates more quickly.
From the next version, knx-ultimate will use knxultimateapi as underlying API.
If you update has solved the issue, can i close this thread?

**Comment by heleon19** [comment] 2020-02-17 13:09
Hello Massimo
Thank you, for your support. 

As a temporary solution I would also use the fork. In the long run it would be better to use the original branch. 

I think you can close the issue now. 

There is one small suggestion regarding "initial read" I still have. I would save the timeouts in a map (obekt with group address as keys). That way you can make sure that the same group addresses are not read twice. The timeouts can be cleaned up during a deployment.
If you want, I can also do a P.R. on them.

Thank you again
Reto

**Comment by Supergiovane** [comment] 2020-02-17 13:16
Hi Reto
About the map, yes it make sense. I'll do for the next release.
About API, the meaning is to switch between knxultimate-api and the original knx.js.
For "emergency" bugfix, i'll patch the knxultimate-api and release a new knx-ultimate version with the patches. As soon as Elias has patched and published the knx.js as well, i'll switch on that.

**Closed by Supergiovane** 2020-02-17 13:16 UTC

**Comment by Supergiovane** [comment] 2020-02-17 14:44
Hi Reto
V. 1.1.31 will be out shortly. I've completely rewritten the "read" matter.

**Comment by RicharddeCrep** [comment] 2021-10-09 02:53
Supergiovane as an observer, I am very impressed with your support.  You could be head of Customer Service in any organisation.

FYI, I also had continual disconnections, but after selected to bind to the wlan(0), all problems disappeared.   I am curious why auto might not (auto) select the best option. ....

Anyway, thanks for a great product.

Two: Questions please:

1.   is there a massive overhead in the code when connecting to multiple GAs, does is absorb exponentially increast the processor loads, or is there a recommended maximum number of GAs Nodes that can be deployed?

2.  Would the accidental presence of two Nodes having the same GA cause issues?   Is it a dangerous activity?  

Thanks again.   Rich
